#!/bin/bash

bokeh_options=""
port=5006

PREFIX=$(dirname $(realpath $0))

if [ -z "$BLUP_CONFIG" ]; then
  BLUP_CONFIG="$HOME/.blup"
fi

usage() {
  cat <<EOF
usage: $0 options [trace_file]

OPTIONS
   -h         Show this message
   -s         Server mode
   -c server  Connect to blup server
   -p         Select the server port
EOF
}

server_mode=n
client_mode=n

while getopts 'shp:c:' OPTION; do
  case $OPTION in
  s)
    server_mode=y
    ;;
  c)
    client_mode=y
    server_name=$OPTARG
    ;;
  p)
    port=$OPTARG
    ;;
  h)
    usage
    exit
    ;;
  esac
done

# remove the options from the command line
shift $(($OPTIND - 1))

if [ "$client_mode" = y ]; then
  trap "ssh -S '$BLUP_CONFIG/blup-tunnel' -O exit $server_name; exit" SIGINT

  echo "Connecting to $server_name:$port"
  ssh -M -S "$BLUP_CONFIG/blup-tunnel" -o "ExitOnForwardFailure yes" -fN -L ${port}:localhost:${port} "$server_name" &
  ssh_pid=$!

  sleep 1
  open http://localhost:${port}

  while true; do
    wait
  done

  exit
fi

###########################
# check is dependencies are installed
###########################
if [ -z "$PYTHON" ]; then
  if which python >/dev/null; then
    PYTHON=$(which python)
  elif which python3 >/dev/null; then
    PYTHON=$(which python3)
  else
    echo "Cannot find python. Please add python or python3 to your PATH, or set PYTHON" >&2
    exit 1
  fi
fi

if pallas_lib=$("$PYTHON" -c "import pallas_trace; print(pallas_trace.__file__)" 2>/dev/null); then
  # Pallas is available. We may need to copy it to the new virtual env.
  echo "Found pallas in $pallas_lib"
fi

# Create/Load a virtual env
if [ ! -d "$BLUP_CONFIG/.venv" ]; then
  echo "Creating a virtual environment $BLUP_CONFIG/.venv"
  "$PYTHON" -m venv "$BLUP_CONFIG/.venv"
fi
echo "Using virtual environment $BLUP_CONFIG/.venv"
echo "(this can be changed by setting BLUP_CONFIG)"

source "$BLUP_CONFIG/.venv/bin/activate"
if which python >/dev/null; then
  PYTHON=$(which python)
elif which python3 >/dev/null; then
  PYTHON=$(which python3)
fi
echo "using $PYTHON as python"

# Install dependencies, if needed
if ! which bokeh >/dev/null; then
  echo "Installing dependencies"
  pip install -r "$PREFIX/requirements.txt"
fi

# Install Pallas, if needed
if ! pallas_local_lib=$("$PYTHON" -c "import pallas_trace; print(pallas_trace.__file__)" 2>/dev/null); then
  if [ -z "$pallas_lib" ]; then
    echo "Cannot find Pallas"
  else
    site_packages=$("$PYTHON" -c 'import site; print(site.getsitepackages()[0])')
    echo "Installing pallas to $site_packages"
    echo ln -s "$pallas_lib" "$site_packages"
    ln -s "$pallas_lib" "$site_packages"
  fi
else
  echo "Found pallas in $pallas_local_lib"
fi

# detect OTF2 path
if ! otf2_local_lib=$("$PYTHON" -c "import otf2; print(otf2.__file__)" 2>/dev/null); then
  if which otf2-config >/dev/null; then
    otf2_python_path=$(otf2-config --pythonpath)
    if [ -n "$otf2_python_path" ]; then
      echo "Found OTF2 in $otf2_python_path"

      site_packages=$("$PYTHON" -c 'import site; print(site.getsitepackages()[0])')
      echo "Installing OTF2 to $site_packages"
      if [ -d "$otf2_python_path/otf2" ]; then
        ln -s "$otf2_python_path/otf2" "$site_packages/otf2"
      fi
      if [ -d "$otf2_python_path/_otf2" ]; then
        ln -s "$otf2_python_path/_otf2" "$site_packages/_otf2"
      fi
    fi
  else
    echo "Cannot find OTF2"
  fi
else
  echo "Found OTF2 in $otf2_local_lib"
fi

###########################
# Run the server
###########################

echo ""

if [ "$server_mode" = n ]; then
  bokeh_options="$bokeh_options --show"
fi

if [ $# -gt 0 ]; then
  args="--args $@"
fi

bokeh serve $bokeh_options "${PREFIX}/blup_server.py" --port=$port $args
